[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.20",
    "reportlab>=4.4.4",
    "uvicorn>=0.38.0",
]
